# Generated by Django 5.0.1 on 2024-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('Descricao', models.CharField(blank=True, max_length=400, null=True, verbose_name='Descrição breve')),
                ('DataDeFinalizacao', models.DateField(null=True)),
                ('DataDeVencimento', models.DateField(verbose_name='Data de vencimento')),
                ('Status', models.CharField(max_length=1, verbose_name='Status')),
            ],
        ),
    ]
