# Generated by Django 5.0.1 on 2024-01-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0002_tarefa_datadecriacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['DataDeVencimento', 'Status']},
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='Status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Pendente', 'Pendente')], max_length=50),
        ),
    ]
