# Generated by Django 5.0.1 on 2024-01-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0003_alter_tarefa_options_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['DataDeVencimento']},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='StatusOrdem',
            field=models.CharField(blank=True, choices=[('Em Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Concluída', 'Concluída')], max_length=50, null=True),
        ),
    ]
