# Generated by Django 5.0.1 on 2024-01-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0004_alter_tarefa_options_tarefa_statusordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='StatusOrdem',
        ),
    ]
