# Generated by Django 5.0.1 on 2024-01-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0005_remove_tarefa_statusordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={},
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='Status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Concluída', 'Concluída')], max_length=50),
        ),
    ]
