# Generated by Django 5.0.1 on 2024-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0006_alter_tarefa_options_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Pendente', 'Pendente')], max_length=50),
        ),
    ]
