# Generated by Django 5.0.1 on 2024-01-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0009_alter_tarefa_datadecriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Status',
            field=models.CharField(choices=[('A', 'Em Andamento'), ('P', 'Pendente')], max_length=1),
        ),
    ]
