# Generated by Django 5.0.1 on 2024-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0011_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='EscolherOrdem',
            field=models.CharField(choices=[('DataDeVencimento', 'Crescente'), ('-DataDeVencimento', 'Decrescente')], max_length=20, null=True),
        ),
    ]
