# Generated by Django 5.0.1 on 2024-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0015_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Pendente', 'Pendente'), ('Concluída', 'Concluída')], max_length=20),
        ),
    ]
