# Generated by Django 5.0.1 on 2024-10-18 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0016_alter_tarefa_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='DataDeFinalizacao',
            new_name='data_de_finalizacao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='DataDeVencimento',
            new_name='data_de_vencimento',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='DataDeCriacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='Descricao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_de_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Breve descrição'),
        ),
    ]
